[package]
name = "xor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
tokio = { version = "1.39.2", features = ["full"] }
ring = "0.17.8"  